### ISSUE TITLE
CDN usage

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-player#102]
I see that unpkg.com is moving away from a `browser` field in package.json, which we're currently using. Have to read up and figure out what the right approach is again…

See https://github.com/unpkg/unpkg/issues/ 63 (whitespace to avoid github linking the issues)

**Comment by u8887** [comment]
Closing since we're using jsdeliver now

**Comment by oskarrough** [comment]
True. And since jsdelivr also uses `browser` field I think we have to keep it for now anyway.

https://github.com/jsdelivr/jsdelivr#publishing-packages
