### ISSUE TITLE
Refactor to new image format

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-player#124]
Now that images have been refactores we no longer need an extra query to fetch it. Instead, whenever we have a channel, we also have an `image` property we can use to build the full Cloudinary URL.

https://github.com/internet4000/radio4000-player/blob/eaf1c8de2875c62c58c647b8f1a0fe68b63d57ff/src/utils/store.js#L53-L61

Note: what we have now still works, as we didn't delete old images yet, so we can do this in time.

**Comment by hugurp** [comment]
It will work, but until someone uploads an image with the new system it will no longer.
The new uploaded image will not be a model but a cloudinary ID, thus creating a conflict between how images were previously referenced and the new system.

It seems that we should run the update it as son as possible, no?

**Comment by oskarrough** [comment]
Good points — and points I didn't consider.

1. The player won't recognize newly uploaded images until this issue is resolved (this issue)
2. For the database migration, what do you think we should do? I have the migration script locally. We could store them in the API repo until/if we need it again? Or the backend repo?
