### ISSUE TITLE
improve touch hit zones for player buttons

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-player#127]
See the filling screenshot, the button touch zone is too small and could be increased.

![screenshot_20181020-080023](https://user-images.githubusercontent.com/1502484/47252072-a66ca900-d43e-11e8-8e82-7d9eb1268102.png)

**Comment by oskarrough** [comment]
Oh yea, I'm all for bigger hit zones.

![proxy duckduckgo](https://user-images.githubusercontent.com/184567/47253811-f6586980-d458-11e8-877a-bf67c9129a42.jpg)

**Comment by hugurp** [comment]
Jas!

**Comment by oskarrough** [comment]
This has been fixed.
