### ISSUE TITLE
mobile /settings/map broken z-ondex with map and player

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-player#128]
See title, minor asf
![screenshot_20181020-230716](https://user-images.githubusercontent.com/1502484/47260564-3998f380-d4be-11e8-98e2-62d4bffe3a6c.png)

**Comment by hugurp** [comment]
Actually maybe a feature :)

**Comment by oskarrough** [comment]
now a days it's on top. either way seems ok
