### ISSUE TITLE
Fullscreen disallowed on youtube

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-player#134]
Seem youtube disallowed puting videos fullscreen.

On the player, and on r4 live.

To investigate

**Comment by oskarrough** [comment]
https://github.com/internet4000/radio4000-player/blob/master/src/YoutubePlayer.vue#L26
https://developers.google.com/youtube/player_parameters#fs

mysterious, why do we set `fs: 0`

**Comment by hugurp** [comment]
ok pushed in the branch, weird. Maybe youtube did not use it before ;D

**Comment by oskarrough** [comment]
Fixed
