### ISSUE TITLE
WIP Release workflow

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-player#40]
Release as "radio4000-player" on NPM starting with version 1.0.0 and from that point following semver?

Example https://infinite-scroll.com/#install

**Comment by hugurp** [comment]
maybe let's just start at version 0.1

**Comment by oskarrough** [comment]
yes, they also recommend it http://semver.org/spec/v2.0.0.html#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase

**Comment by oskarrough** [comment]
OK, how about this

- [x] add `browser` field to `dist/radio4000-player.min.js`
- [ ] rename repo to `radio4000-player`
- [ ] tag as `0.1.0`
- [ ] remove `private` field in package.json
- [ ] add `files: ` array with `dist
- [ ] publish to npm (it will take the `name` from package.json so `radio4000-player`)

now you have a couple of ways to use it:

## CDN

get the latest:

```html
<script src="https://unpkg.com/radio4000-player/dist/radio4000-player.min.js"></script>
<script src="https://unpkg.com/radio4000-player/dist/radio4000-player.js"></script>
```

or a specific version:

```html
<script src="https://unpkg.com/radio4000-player@1/dist/radio4000-player.min.js"></script>
<script src="https://unpkg.com/radio4000-player@1/dist/radio4000-player.js"></script>
```

## Download

- https://unpkg.com/radio4000-player/dist/radio4000-player.min.js
- https://unpkg.com/radio4000-player/dist/radio4000-player.js

## Package managers

npm: `npm install radio4000-player` 
yarn: `yarn add radio4000-player`

---

In any case, you can now do 

```html
<radio4000-player channel-slug="200ok"></radio4000-player>
```

When we want to publish a new version, we will do

1. `yarn build`
2. `git tag x.x.x` (following semver as best as we can)
3. `npm publish`

We currently check in the `dist/` folder to git. We *could* avoid this by using the `files` field in package.json which makes sure npm includes those files even if in gitignore. But I kinda like having the built ready file in git. See the bottom of this page https://unpkg.com/#/. This workflow is also new to me so any feedback is appreciated!

**Comment by hugurp** [comment]
ok

**Comment by hugurp** [comment]
lgtm

**Comment by oskarrough** [comment]
Released on https://www.npmjs.com/package/radio4000-player
