### ISSUE TITLE
Ideas for improvements

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-player#69]
Let's discuss what we'd like to improve in the player. I can start...

- font-size in header could be 1em for both radio title + track title
- font-size in track list is too small
- do we need a "previous" button?
- can we find unicons for shuffle + prev/next that have the same thickness?
- how would a non-savy user share a radio/track? Are the flows different when you're listening on R4 and when it's just the player?

**Comment by hugurp** [comment]
Let's also remember to focus on what is **really** important for the player, and for r4.
Design has to always come up after usability and good non-overwhelming features.
