### ISSUE TITLE
Deleted tracks are being shown?

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-player#70]
Reproduce:

1. Go to https://radio4000.com/oskar
2. Play it
3. If you scroll ~10-20 tracks down in the player (not Radio4000) you'll see lots of "Newcleus" tracks

I created and deleted this track many times while I was testing something. The tracks are NOT appearing in the channel model. But they are still in /tracks. And since the way the player queries tracks is `radio4000.firebaseio.com/tracks.json?query...` and not through `/channels/oskar/tracks` we also get tracks that the channel does not have.

What can we do?

We could query `channels/id/tracks.json` and send a request for each and every one. But that doesn't seem good.

**Comment by hugurp** [comment]
we can filter both lists...

**Comment by hugurp** [comment]
hum, everything seems to be working fine though https://github.com/internet4000/radio4000/blob/master/app/channel/index/controller.js#L54

**Comment by oskarrough** [comment]
yes it's only when we do

```js
var url = `${host}/tracks.json?orderBy="channel"&startAt="${id}"&endAt="${id}"`
```
from https://github.com/internet4000/radio4000-player/blob/master/src/utils/store.js#L41

**Comment by hugurp** [comment]
I don't understand why, since deleting a track is this function:
```
		deleteTrack(track) {
			const flashMessages = get(this, 'flashMessages');
			this.send('closeModals');
			track.get('channel').then(channel => {
				channel.get('tracks').then(() => {
					track.destroyRecord().then(() => {
						flashMessages.warning('Track deleted');
					}, () => {
						flashMessages.warning('Could not delete your track');
					});
				});
			});
		}
```

**Comment by oskarrough** [comment]
OK. Closing thinking it was just the test tracks I did while testing the above function.

**Comment by oskarrough** [comment]
https://radio4000.com/samro has the same issue with at least one track. Reopening.

**Comment by oskarrough** [comment]
Closing again. Removed the missing track from the channel `samro` directly in the DB.
