### ISSUE TITLE
Tapping first track doesn't play

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-player#73]
By default without `autoplay` the latest track is active but not playing. If you then tap it in the list to play, nothing happens.

Clicking play on the YouTube video or our own play button works.

**Comment by oskarrough** [comment]
now that I look at it, I think it doesn't play because its youtube-id is already loaded in the player at this point… which leads to --> https://github.com/internet4000/radio4000-player/issues/79

**Comment by hugurp** [comment]
if you tap it nothing should happen. Pressing play on a play button (video || ours) should start playback session.

**Comment by oskarrough** [comment]
Closing
