### ISSUE TITLE
Tracks sometimes don't play continuously

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-player#76]
as noticed by @jfalxa , the player sometimes do not play next track when one finishes. It seems to just stop.

Let's try to reproduce and find out why.

**Comment by oskarrough** [comment]
Could it be we are forgetting to call `next()` when there's a player error like geo-restriction or a missing video?

**Comment by hugurp** [comment]
could not reproduce. closing for now, will open new when issue occurs. Not good to have criptic possible long standing issues
