### ISSUE TITLE
play/pause infinite loop error

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-player#80]
The player will get into an infinite loop between **play** and **pause** modes when:
- triple click on the Youtube video
- double click on the Youtube progress bar

Bugs stops if you click again on the progress bar.

**Comment by oskarrough** [comment]
Fixed in https://github.com/internet4000/radio4000-player/commit/f0bc6b7dd567f97bfdb6c9b1e53eae0ff2d523d3
