### ISSUE TITLE
Long word in track get track item and track list

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-player#89]
![deepinscreenshot_select-area_20171216130851](https://user-images.githubusercontent.com/1502484/34070212-3fc2f3a4-e262-11e7-8177-78d30e5300e6.png)

**Comment by oskarrough** [comment]
Which browser is it? It breaks here in my Chrome 63 desktop/windows.

**Comment by hugurp** [comment]
sorry, FF arch linux

**Comment by oskarrough** [comment]
We're using `word-break: break-word`. Which works in Chrome, but doesn't seem to be part of the spec: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

Can you verify`word-break: break-all` on the track description? It seems to fix it.

**Comment by hugurp** [comment]
It fixes it, but it has this behavior of cutting a word in its middle.

maybe ?
https://stackoverflow.com/questions/15261605/how-to-use-automatic-css-hyphens-with-word-break-break-all#15263285
```
    -moz-hyphens: manual;
    -ms-hyphens: manual;
    hyphens: manual;
```

**Comment by oskarrough** [comment]
It it fixed by https://github.com/internet4000/radio4000-player/commit/017adc827f274093c47d1e29fd38f14901db6d4c or does the hypens-thing work better?

**Comment by hugurp** [comment]
fixed
