### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-player#90]
I just noticed that <radio4000-player> doesn't even render in IE11. It's because that browser is missing support for `Object.assign`, which is used somewhere.

Do we fix it? It's probably just configuring babel browser support.
Or do we leave it and say for modern browsers only?

![ie11](https://user-images.githubusercontent.com/184567/34070429-455e125e-e266-11e7-9229-5a35e994b5d7.PNG)

- [ ] Make it work in Edge + IE11

**Comment by hugurp** [comment]
if it is a babel thing, would be cool to give even ie9 support

**Comment by oskarrough** [comment]
We can configure it here https://github.com/internet4000/radio4000-player/blob/master/.babelrc#L6. Will try it one day and test on Windows.

**Comment by u8887** [comment]
Should I work on this? I'm not sure what the status is.

I can do a browser stack session

**Comment by oskarrough** [comment]
Made a quick check: the player doesn't work at all in Internet Explorer 11. Maybe it is an easy fix?

But every time I open IE11, it prompts me to install Edge. So I don't think we need to spend time fixing a deprecated browser. As long as it works in newer ones + most mobile devices I'm happy camper.
