### ISSUE TITLE
Improve release workflow

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-player#97]
To make this package available on CDNs like jsdelivr and unpkg we push a built and minified version to GitHub in `dist/radio4000-player.min.js`.

The problem is that it doesn't happen automatically and we (well, I) forget to build before publishing to NPM.

We tried a `prepublishOnly` hook, which runs before publishing to NPM, but it doesn't make sure that the built file is included in the commit. So doesn't work.

What to do?

**Comment by oskarrough** [comment]
Here's what we want to do when we release:

1. Bump version in package.json
2. Run `npm build` to create a new `dist/radio4000.min.js` file
3. Create a new "release" commit
4. Push to git
5. Publish to NPM

Currently the problem is that 2) only runs on "prepublish", which is too late in the flow as the built file won't be included in the commit.

SO… the [`release-it`](https://github.com/webpro/release-it) package can do this for us.

1. Install `release-it` as dev dependency
2. Create a package.json script:

```
"release": "release-it --buildCommand 'npm build'"
```

Now, we can do everything in one command like

```
npm run release # defaults to patch
npm run release minor
npm run release major
npm run release 1.2.5 # custom version
```

Tested it here https://github.com/oskarrough/release-test/blob/master/package.json

**Comment by hugurp** [comment]
Solution lgtm!
It is a Dev dependency, so not that bad as it does not add weight to the served file.
Gg :)
