### ISSUE TITLE
Setup a radio4000-player website

### ISSUE THREAD

**Issue by hugurp** [internet4000/radio4000-player#99]
I think it could be extremely useful for the following reasons:

- adds a URL to present the player and its capacities, anyways we already have one to test during development (we can this URL to the Github repo, we can have a subdomain on r4 too player.radio4000.com)
- with a Netlify setup it gives a URL for each pull request
- can be setup to auto-deploy on production branch
- can help us make a better CI and deployment to npm pipeline

**Comment by hugurp** [comment]
Both?

**Comment by oskarrough** [comment]
fooling around https://tall-point.glitch.me. put the readme in there just to have something but I feel it needs to be rethought if we want it on a website.

https://glitch.com/edit/#!/tall-point?path=index.html:3:0

we could have two (or more) .html files with different purpose. one for development like we have now and another that is a bit more fancy, explains features etc.

**Comment by oskarrough** [comment]
inspiration

- http://sketchmachine.net/
- https://atom.io/

**Comment by oskarrough** [comment]
We also ahve https://player.radio4000.com and https://github.com/internet4000/radio4000-embed-generator

**Comment by oskarrough** [comment]
for reference, it is  here https://github.com/internet4000/radio4000-player/blob/master/demo/index.html

**Comment by hugurp** [comment]
how do you like this quick solution?
Could use some better styling, but at least there is something to point to

**Comment by oskarrough** [comment]
Yea maybe, but it's great for me. Info is there, example is there, documentation is there.
